name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Teste completo
      id: teste-completo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Teste completo
        setup-command: ''
        command: make test-all
        timeout: 2
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTE-COMPLETO_RESULTS: "${{steps.teste-completo.outputs.result}}"
      with:
        runners: teste-completo
